PlotStdCurve <- function(filedir = "summarizedTt.csv",
                         xlabel = expression("log"[10]*"concentraion"~ "("*"Copies /" ~ mu*L*")"), ylabel= "Tt (min)", 
                         trend.start.row = 1, trend.end.row = nrow(tt),
                         points.col = "blue", line.col = "red",
                         legendx = "topright", legendy = NULL,
                         img.save = F, img.width = 300, img.height = 250) {
    # Plot a standard curve using the Tt values.
    # 
    # Args:
    #   filedir: the directory of a csv file containing the mean and standard error of Tts in each group;
    #            this file can be generated by SummariseTt().
    #   xlabel: x axis label of the standard curve.
    #   ylabel: y axis label of the standard curve.
    #   trend.start.row: from which row the Tt values will be plotted on the standard curve.
    #   trend.end.row: to which row the Tt values will be plotted on the standard curve.
    #   points.col: the color of points on the standard curve.
    #   line.col: the color of the fitted line on the standard curve.
    #   legendx: the x location to put the legend. Default is topright. 
    #   legendy: the y location to put the legend.
    #   img.save: if TRUE, save the standard curve to a png file; if not, not. Default is FALSE.
    #   img.width: if img.save, what is the width of the image.
    #   img.height: if img.save, what is the height of the image.
    #
    # Returns:
    #   r.square: r^2 of the fitted line.
    #   adj.r.square: adjucted r^2 of the fitted line.
    #   beta0: intercept of the regression line.
    #   beta1: slope of the regression line.
    
    tt <- read.csv(filedir)
    lm.fit <- lm(tt$means[trend.start.row:trend.end.row] ~ tt$concentrations[trend.start.row:trend.end.row])
    r.square     <- round(summary(lm.fit)$r.squared, 3)
    adj.r.square <- round(summary(lm.fit)$adj.r.squared, 3)
    beta0        <- round(summary(lm.fit)$coef[1], 2)
    beta1        <- round(summary(lm.fit)$coef[2], 2)
    
    # Plotting
    plot(x = tt$concentrations, y = tt$means,
         type = "n", ylim = c(0, 60),
         xlab = xlabel, ylab = ylabel)
    points(x = tt$concentrations, y = tt$means, 
           pch = 19, col = points.col)
    abline(lm.fit, 
           col = adjustcolor(line.col, alpha = 0.5), lwd = 2)
    legend(x = legendx, y = legendy, bty = "n", legend = bquote(R^2 == .(r.square)))
    arrows(tt$concentrations, tt$means - tt$se, 
           tt$concentrations, tt$means + tt$se, 
           length = 0.05, angle = 90, code = 3)
    
    # Saving image
    if (img.save) {
        dev.copy(png, file = "standcurve.png", 
                 width = img.width, height = img.height)
        dev.off()
    }
    result <- list("r.square"     = r.square, 
                   "adj.r.square" = adj.r.square,
                   "beta0"        = beta0,
                   "beta1"        = beta1)
    return(result)
}
