SummariseTt <- function(filedir = "tt.csv", save2file = T) {
    # Summarise the threshold time (Tt) by calculating the mean and standard error of Tts in each group
    # 
    # Args:
    #   filedir: the directory of a csv file containing a data frame of the threshold times for all reacted groups; 
    #            this file could be generated by FindParams().
    #   save2file: if TRUE, save the summarized data frame (mean and ste of each group) in "summarisedTt.csv"; if not, not. Default is TRUE.
    # Returns:
    #   --
    
    library(dplyr)
    library(tidyr)
    threshold.time <- tbl_df(read.csv(filedir)) %>%
        separate(groups, c("concentrations", "replicates")) %>%
        mutate(concentrations = extract_numeric(concentrations)) %>%
        group_by(concentrations) %>%
        select(concentrations, replicates, threshold)
    summarise.tt <- summarise(threshold.time, 
                              means = mean(threshold), 
                              se = sd(threshold)/sqrt(length(threshold)))
    if (save2file) {
        write.csv(summarise.tt, "summarizedTt.csv")
    }
}